package com.won.autoinvestor.common.trade;

public enum LifecycleEventType {
    BUY_FILLED,
    LIFECYCLE_STARTED,
    WHITE_ENTERED,
    WHITE_TO_GRAY,
    GRAY_DAY_COUNTED,
    WHITE_RECOVERED,
    BLACK_ENTERED,
    REFERENCE_PRICE_UPDATED,
    AVERAGE_BUY_PRICE_UPDATED,
    PARTIAL_SELL_FILLED,
    TAKE_PROFIT_TRIGGERED,
    STOP_LOSS_TRIGGERED,
    SELL_ORDER_CREATED,
    SELL_FILLED,
    CLOSED,
    ORDER_FAILED,
    ORDER_CANCELLED,
    STRATEGY_ERROR
}
